config/routes.rb
Rails.application.routes.draw do
  get 'tag/index'
  get 'tag/show'
  resources :papers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => "papers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paper.rb
class Paper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:title, :authors, :abstract, :notes, :bibtex, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bibop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/papers/_form.html.erb
<%= form_with(model: paper, local: true) do |form| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
        <% paper.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.text_field :authors %>
  </div>

  <div class="field">
    <%= form.label :abstract %>
    <%= form.text_area :abstract %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :bibtex %>
    <%= form.text_area :bibtex %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_area :tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Papers</h1>
<%= link_to 'New Paper', new_paper_path %>
<br>

<table class="table table-striped" id="papers-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Authors</th>
      <th>Abstract</th>
      <th>Notes</th>
      <th>Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= link_to paper.title, paper %></td>
        <td><%= paper.authors %></td>
        <td><%= paper.abstract %></td>
        <td><%= paper.notes %></td>
        <td><%= paper.tags %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Authors:</strong>
  <%= @paper.authors %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @paper.abstract %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>